version: '3'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/students

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: students
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
